#!/bin/bash
#Jeannie Chiem
#'gnyorly@gmail.com'
#ID:504666652


default:
	gcc -Wall -Wextra -g lab1a.c -o lab1a

clean:
	rm -f lab1a lab1a-504666652.tar.gz

dist: 
	tar -czvf lab1a-504666652.tar.gz Makefile README.txt lab1a.c

